version: '3.8'

services:
  # In-Memory Broker & Cache
  redis:
    image: redis:7-alpine
    container_name: shieldapi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Core API Gateway / Proxy
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    container_name: shieldapi-gateway
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BACKEND_SERVICE_URL=http://backend-service:8001
    depends_on:
      redis:
        condition: service_healthy
      backend-service:
        condition: service_started
    volumes:
      - shared_logs:/var/log/shieldapi

  # Anomaly Guardian (Background Log Analysis Engine)
  anomaly-engine:
    build:
      context: .
      dockerfile: ./apps/anomaly-engine/Dockerfile
    container_name: shieldapi-anomaly-engine
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_FILE_PATH=/var/log/shieldapi/access.log
    depends_on:
      redis:
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
      - shared_logs:/var/log/shieldapi

  # Protected Backend Microservice (Dummy Target)
  backend-service:
    build:
      context: .
      dockerfile: ./apps/backend-service/Dockerfile
    container_name: shieldapi-backend-service
    ports:
      - "8001:8001"

  # Admin Dashboard UI
  dashboard:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    container_name: shieldapi-dashboard
    ports:
      - "3000:80"
    depends_on:
      - gateway

volumes:
  redis_data:
  shared_logs:
